"""Leakage-guarded, onset-conditioned adaptation for the V5 stored-time operator."""

from .contracts import (
    SnapshotAccessAudit,
    SyntheticBridgeProvenance,
    future_indices,
    onset_indices,
)
from .data_guard import GuardedOnsetDataset, GuardedOnsetRecord
from .adapters import LowRankFieldResidual, OnsetAdaptedV5, OnsetSnapshotConditioner, ZeroInitLoRA
from .bridge import BridgeResult, make_onset_bridge
from .losses import (
    LossWeights,
    PhysicsPointSet,
    PhysicsSampling,
    build_fixed_physics_points,
    build_rad_physics_points,
    build_r3_rams_physics_points,
    instance_loss_terms,
    lwc84_residual,
    sample_fixed_physics_residual,
)
from .trainer import AdaptationResult, adapt_instance
from .chonknoris import (
    CholeskySupervision,
    ReducedCholeskyPredictor,
    ReducedChonknorisConfig,
    ReducedChonknorisResult,
    reduced_chonknoris_solve,
    supervise_cholesky_factor,
)
from .residual_iterator import (
    RESIDUAL_ITERATOR_SCHEMA_VERSION,
    MultiScaleResidualCorrector,
    ResidualIteratorLossWeights,
    ResidualIteratorResult,
    align_lwc84_residual,
    refine_with_residual_iterator,
    residual_iterator_training_loss,
    unroll_residual_iterator,
)
from .forced_defect import (
    SavedGridCPMLConfig,
    laplacian8,
    lwc84_discrete_defect,
    lwc84_source_terms,
    lwc84_step,
    saved_grid_cpml_config,
)
from .defect_correction import (
    CPADC_SCHEMA_VERSION,
    CausalErrorBasisGenerator,
    ConvexDefectCorrectionResult,
    DefectCorrectionWeights,
    FactorizedCausalBasis,
    MetaDefectLossWeights,
    WeightedRidgeResult,
    causal_observation_probe_basis,
    causal_smoothstep_envelope,
    meta_defect_correction_loss,
    sampled_basis_defect_design,
    solve_causal_defect_correction,
    solve_weighted_ridge,
)
from .visualization import derive_receivers_from_field, plot_receiver_comparison, plot_wavefield_comparison

__all__ = [
    "SnapshotAccessAudit",
    "SyntheticBridgeProvenance",
    "future_indices",
    "onset_indices",
    "GuardedOnsetDataset",
    "GuardedOnsetRecord",
    "LowRankFieldResidual",
    "OnsetAdaptedV5",
    "OnsetSnapshotConditioner",
    "ZeroInitLoRA",
    "BridgeResult",
    "make_onset_bridge",
    "LossWeights",
    "PhysicsPointSet",
    "PhysicsSampling",
    "build_fixed_physics_points",
    "build_rad_physics_points",
    "build_r3_rams_physics_points",
    "instance_loss_terms",
    "lwc84_residual",
    "sample_fixed_physics_residual",
    "AdaptationResult",
    "adapt_instance",
    "CholeskySupervision",
    "ReducedCholeskyPredictor",
    "ReducedChonknorisConfig",
    "ReducedChonknorisResult",
    "reduced_chonknoris_solve",
    "supervise_cholesky_factor",
    "RESIDUAL_ITERATOR_SCHEMA_VERSION",
    "MultiScaleResidualCorrector",
    "ResidualIteratorLossWeights",
    "ResidualIteratorResult",
    "align_lwc84_residual",
    "refine_with_residual_iterator",
    "residual_iterator_training_loss",
    "unroll_residual_iterator",
    "laplacian8",
    "SavedGridCPMLConfig",
    "lwc84_discrete_defect",
    "lwc84_source_terms",
    "lwc84_step",
    "saved_grid_cpml_config",
    "CPADC_SCHEMA_VERSION",
    "CausalErrorBasisGenerator",
    "ConvexDefectCorrectionResult",
    "DefectCorrectionWeights",
    "FactorizedCausalBasis",
    "MetaDefectLossWeights",
    "WeightedRidgeResult",
    "causal_observation_probe_basis",
    "causal_smoothstep_envelope",
    "meta_defect_correction_loss",
    "sampled_basis_defect_design",
    "solve_causal_defect_correction",
    "solve_weighted_ridge",
    "derive_receivers_from_field",
    "plot_receiver_comparison",
    "plot_wavefield_comparison",
]
