#!/usr/bin/env bash
# Audited four-GPU reflection continuation on the train/Marmousi-replaced v5 VDS.
# The dense objective uses every stored spatial site (201 x 201); TRAINING_FRAMES
# controls the exact temporal samples per record.
set -Eeuo pipefail

REPO_ROOT=/root/autodl-tmp/work/FNO-Acoustic-Wave-Simulation/grouped-dual-head-v2
MIXED_ROOT=/root/autodl-tmp/data/jiayh/data/acoustic_lwc84_2km_401x401_to_201_train_marmousi_hires_v5_dt1e5_t401_mixed
MARM_CACHE="$MIXED_ROOT/background_pbg_sigma2_marm700_full401"

export ORIGINAL_REFLECTION_SOURCE_H5="$MIXED_ROOT/dataset_v5_dt1e5_t401_mixed.h5"
export ORIGINAL_REFLECTION_SOURCE_REPLACEMENT_GATE="$MIXED_ROOT/mixed_protocol_replacement_gate.json"
export ORIGINAL_REFLECTION_TRAVEL_TIME_H5="$MIXED_ROOT/hybrid_travel_train_validation_v5.h5"
export ORIGINAL_REFLECTION_BACKGROUND_CACHE="$MARM_CACHE/shard-0.h5"
export ORIGINAL_REFLECTION_BACKGROUND_CACHE_SHARDS="$MARM_CACHE/shard-1.h5:$MARM_CACHE/shard-2.h5:$MARM_CACHE/shard-3.h5:/dev/shm/g3cache/background_pbg_sigma2_g3pool_N420.h5"

# One guarded epoch over 420 uniform + 420 layered + all 700 replacement
# Marmousi records.  Effective global batch = 8 records/macro * 4 DDP macros.
export ORIGINAL_REFLECTION_EPOCHS="${ORIGINAL_REFLECTION_EPOCHS:-1}"
export ORIGINAL_REFLECTION_MACRO_RECORDS="${ORIGINAL_REFLECTION_MACRO_RECORDS:-8}"
export ORIGINAL_REFLECTION_MACROS_PER_UPDATE="${ORIGINAL_REFLECTION_MACROS_PER_UPDATE:-4}"
export ORIGINAL_REFLECTION_MICROBATCH_RECORDS="${ORIGINAL_REFLECTION_MICROBATCH_RECORDS:-1}"
export ORIGINAL_REFLECTION_TRAINING_FRAMES="${ORIGINAL_REFLECTION_TRAINING_FRAMES:-96}"
export ORIGINAL_REFLECTION_VALIDATION_FRAMES="${ORIGINAL_REFLECTION_VALIDATION_FRAMES:-401}"
export ORIGINAL_REFLECTION_EVALUATE_EVERY="${ORIGINAL_REFLECTION_EVALUATE_EVERY:-97}"
export ORIGINAL_REFLECTION_UNIFORM_RECORDS="${ORIGINAL_REFLECTION_UNIFORM_RECORDS:-420}"
export ORIGINAL_REFLECTION_LAYERED_RECORDS="${ORIGINAL_REFLECTION_LAYERED_RECORDS:-420}"
export ORIGINAL_REFLECTION_MARMOUSI_RECORDS="${ORIGINAL_REFLECTION_MARMOUSI_RECORDS:-700}"
export ORIGINAL_REFLECTION_UNIFORM_SAMPLING_WEIGHT="${ORIGINAL_REFLECTION_UNIFORM_SAMPLING_WEIGHT:-0.1}"
export ORIGINAL_REFLECTION_LAYERED_SAMPLING_WEIGHT="${ORIGINAL_REFLECTION_LAYERED_SAMPLING_WEIGHT:-1.0}"
export ORIGINAL_REFLECTION_MARMOUSI_SAMPLING_WEIGHT="${ORIGINAL_REFLECTION_MARMOUSI_SAMPLING_WEIGHT:-1.0}"
export ORIGINAL_REFLECTION_DIRECT_FREQUENCY_HEAD="${ORIGINAL_REFLECTION_DIRECT_FREQUENCY_HEAD:-1}"
export ORIGINAL_REFLECTION_DIRECT_FREQUENCIES="${ORIGINAL_REFLECTION_DIRECT_FREQUENCIES:-32}"

exec "$REPO_ROOT/scripts/run_helmholtz_reflection_recovery_original_stage2_ddp4.sh"
